djangocms_link/models.py

This allows to leave all fields blank except anchor to put an anchor to the page the link is on.

Allow to put anchor links targetting the current page

---

djangocms_link/models.py
djangocms_link/validators.py

Provides support for *additional* hostname patterns by configuring the setting: DJANGOCMS_LINK_INTRANET_HOSTNAME_PATTERN
This is useful for intranet environments where it is valid to reference NETBIOS or NETBEUI, et al names across the network.
The setting should contain a valid regex pattern, here's some samples:
RFC1123: `r'[a-z,0-9,-]{1,15}'`
NetBIOS: `r'[a-z,0-9,!@#$%^()\\-\'{}.~]{1,15}'`

Support internal hosts

---

djangocms_link/validators.py

Removes the `deconstructible` decorator for Django 1.6 compatibility.

Django 1.6 compatibility

---

djangocms_link/migrations_django/0004_auto_20150708_1133.py

@mkoistinen It seems you forget create migration after changes in `Link.anchor.help_text` and `Link.url`: https://github.com/divio/djangocms-link/commit/d1a48c9e737972d52e0e73f04b729f1b8be316a7 https://github.com/divio/djangocms-link/commit/3d0b712d87386915a6032ddba963a086130af585

link model django migration

---

.gitignore
CHANGELOG.rst
setup.py

Django Select2 version 5.0 is not compatible with Django 1.6.

Pin select2 version

---

CHANGELOG.rst
djangocms_link/forms.py

Since https://github.com/divio/djangocms-attributes-field/pull/14/
it is no longer required to pass custom width for the input since
it is going to be handled correctly by the field itself.

Fixed styling issues with attributes field

---

addon.json
tox.ini

We assume `django_select2` has been setup by Aldryn Django CMS

Added aldryn config

---

CHANGELOG.rst
djangocms_link/migrations/0010_adapted_fields.py
djangocms_link/migrations/0011_fixed_null_values.py
djangocms_link/migrations/0012_removed_null.py

This needed further adaptions to work on the following scenarios:
- Install the addon from scratch
- Upgrading the addon from 1.8.3 to 2.0.0 and then 2.0.1
- Upgrading the addon from 2.0.0 to 2.0.1
- Upgrading the addon from failing (IntegrityError) 2.0.0 to 2.0.1

Fixed django.db.utils.IntegrityError issues

---

.travis.yml
CHANGELOG.rst
README.rst
djangocms_link/migrations/0004_auto_20150708_1133.py
djangocms_link/migrations/0010_adapted_fields.py
djangocms_link/migrations/0013_fix_hostname.py
djangocms_link/validators.py
tox.ini

* Prevent changes to ``DJANGOCMS_LINK_XXX`` settings from requiring new
migrations
* Changed naming of ``Aldryn`` to ``Divio Cloud``
* Adapted testing infrastructure (tox/travis) to incorporate
django CMS 3.4 and dropped 3.2
* Removed NetBios Pattern from documentations as its faulty

adapted testing infrastructure, fixed migrations and docs

---

CHANGELOG.rst
djangocms_link/__init__.py

* Prevent changes to ``DJANGOCMS_LINK_XXX`` settings from requiring new
migrations
* Changed naming of ``Aldryn`` to ``Divio Cloud``
* Adapted testing infrastructure (tox/travis) to incorporate
django CMS 3.4 and dropped 3.2
* Removed NetBios Pattern from doccd umentations as its incorrect

Release version 2.0.3

---

.gitignore
CHANGELOG.rst
djangocms_link/fields.py
djangocms_link/fields_select2.py
djangocms_link/fields_select2_legacy.py
tests/requirements.txt
tests/settings.py
tests/tests_field.py

This is a proposal. I think we should discuss about my way of supporting the old versions of django-select2 for backward compatibility. And I see some unwanted style problems (incompatible input view with other inputs).
And the other thing, I couldn't find any use of `UserSearchField`. Should we keep this method or remove it completely?

we started to support new django-select2 versions. #78

---

djangocms_link/forms.py
djangocms_link/models.py

Validates that only one of the link-ish fields can be filled at the same
time.
Respects special cases with anchor.
(*Sorry for mixed languages in screenshots*)

Better link validation

---

CHANGELOG.rst
djangocms_link/__init__.py

* Fixed a bug which prevented links from working when the page
referenced is on a different site from the one that contains the plugin.

Release version 2.1.2

---

djangocms_link/models.py

Use `Site.domain` instead of `str(Site)` when generating urls.
I have overridden `Site.__str__` and the latest version of this plugin started generating invalid urls.

Fixed link urls when Site.__str__ is overridden.

---

djangocms_link/models.py

Fix spurious warning messages "cms/models/pluginmodel.py:308: DontUsePageAttributeWarning: Don't use the page attribute on CMSPlugins! CMSPlugins are not guaranteed to have a page associated with them!".
They were emitted from https://github.com/divio/django-cms/blob/3.4.4/cms/models/pluginmodel.py#L304
called from https://github.com/divio/djangocms-link/blob/2.1.2/djangocms_link/models.py#L138
Also this pull-request may fix #133

Fixed DontUsePageAttributeWarning message

---

CHANGELOG.rst
djangocms_link/__init__.py

* Fixed test matrix
* Fixed an issue when ``page.site`` is not available
* Fixed an issue generating ``'Page' object has no attribute 'site'``

Bumped version to 2.3.0

---

CHANGELOG.rst
djangocms_link/__init__.py

* Added file link support
* Allow link requirement to be changed when another
CMS plugin inherits from AbstractLink
* Fixed a bug preventing ``HOSTNAME_PATTERN`` to work

Bumped version to 2.5.0

---

CHANGELOG.rst
djangocms_link/__init__.py

* Added support for Django 3.0
* Added support for Python 3.8
* Pinned ``django-filer`` to 1.5.0
* Added further tests to raise coverage
* Fixed smaller issues found during testing
* Dropped support for django-select2 <= 4
* Dropped support for django-filer <= 1.4

Bumped version to 2.6.0

---

djangocms_link/cms_plugins.py

This error occurred to me when using djangocms_bootstrap4 Carousel whenever editing one of the Slider forms. (Installed fresh djangocms 3.7.2 with djangocms-installer)

fixed #183: AttributeError: 'Page' object has no attribute 'site'

---

CHANGELOG.rst
djangocms_link/fields_select2.py

The default label for select2 items are the Page's [`__str__` method](https://github.com/django-cms/django-cms/blob/develop/cms/models/pagemodel.py#L256), which displays the page's menu title.
It happens frequently that several pages share the same menu title: they are therefore indistinguishable from each other.
This pull request displays the page's title instead of the menu title.

Display page title instead of menu title

---

.github/workflows/test.yml
CHANGELOG.rst
djangocms_link/models.py
tests/requirements/dj40_cms311.txt

django-cms 3.11 adds the support of django 4.0 but currently djangocms-link is not compatible with this version of django as there is use of force_text in the codebase. So we remove the use of this deprecated method in favor of `force_str`.
* https://github.com/django-cms/django-cms/blob/release/3.11.x/CHANGELOG.rst#highlights
* https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

fix: add support of django 4.0

---

CHANGELOG.rst
tests/test_plugins.py

The deprecated aliases have been removed in python/cpython#28268

Use assertEqual instead of assertEquals for Python 3.11 compatibility.

---

README.rst

Add a "migrate from cmsplugin" management command mention in README.
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

DOCS: update README

---

djangocms_link/fields_select2.py
djangocms_link/forms.py
djangocms_link/helpers.py
tests/fixtures.py
tests/settings.py
tests/test_migrations.py
tests/test_plugins.py
tox.ini

This PR adds support for the new djangoCMS 4.x.
It closes #221 and uses the outlined approach discussed there.
I also refactored the test setup and added the Mixin/Fixture of djangocms-text-ckeditor4 to support both djangoCMS 3 & 4.
All tests are green locally, I'd be happy to get this merged if everything is looking good to you @fsbraun :)
* https://github.com/django-cms/djangocms-text-ckeditor/blob/master/tests/fixtures.py
* [ x ] I have opened this pull request against ``master``
* [ x ] I have added or modified the tests when changing logic
* [ x ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ x ] I have read the [contribution guidelines …

Add support for djangoCMS 4.x
