django-cms/djangocms-link

setup.py
see also:
https://github.com/nephila/djangocms-blog/pull/80
=> Fix conditional dependencies when using wheels

djangocms_link/fields.py, djangocms_link/forms.py
=> Fix early queryset trigger

djangocms_link/models.py, djangocms_link/tests/tests_model.py
=> Fix tel schema. Fix #53

.editorconfig, .travis.yml, djangocms_link/cms_plugins.py, djangocms_link/fields.py, djangocms_link/models.py, djangocms_link/tests/tests_model.py, djangocms_link/validators.py, setup.cfg, test_settings.py, tox.ini
=> Fix matrix

CHANGELOG.rst, djangocms_link/__init__.py
* Added additional settings
* Added configuration option for select2
* Cleaned up file structure
* Removed Django < 1.8 support
* Adapted ``README.txt``
* Fixed an issue where links appear twice
=> Release 2.0.0

CHANGELOG.rst, djangocms_link/__init__.py
* Fixed an issues with migrations where Null values caused ``IntegrityError``
=> Released version to 2.0.1

.editorconfig, CHANGELOG.rst
* Fixes https://github.com/divio/djangocms-link/issues/101
* Adds editorconfig setting for newline problem on link.html file
=> Adaptions to readme and editorconfig

CHANGELOG.rst, djangocms_link/__init__.py
* Fixed an issue with ``target`` attribute
=> Release 2.0.2

CHANGELOG.rst, djangocms_link/models.py
Fix :AttributeError: 'Options' object has no attribute 'get_field_by_name'
=> Adds compatibility for django 1.10 

CHANGELOG.rst, djangocms_link/models.py
=> Added better link validation

CHANGELOG.rst, djangocms_link/__init__.py
* Added compatibility for django 1.10
* Added better validation to set a link
* Added support for django-select2 5.x
* Removed unused ``UserSearchField``
=> Release version 2.1.0

CHANGELOG.rst, djangocms_link/models.py
Fix issue #115 : AttributeError: 'Options' object has no attribute 'get_field_by_name
Idem PR #111
=> Added compatibility for django 1.10

djangocms_link/fields_select2.py, djangocms_link/fields_select2_legacy.py, djangocms_link/forms.py
=> Fixed #118 -- Use correct field subclass

CHANGELOG.rst, djangocms_link/cms_plugins.py, djangocms_link/models.py
=> Fixed #121 -- Use absolute urls for link which spans to different site

.travis.yml, CHANGELOG.rst, djangocms_link/cms_plugins.py, djangocms_link/models.py, setup.py, tests/settings.py, tox.ini
* Fixed test matrix
* Fixed an issue when ``page.site`` is not available
* Fixed an issue generating ``'Page' object has no attribute 'site'``
* Fixes #154
=> Adapted test matrix and fixes issue with Django 2.x

CHANGELOG.rst, djangocms_link/models.py
=> Fixes an issue when ``cms_page`` is not available

CHANGELOG.rst, djangocms_link/__init__.py
* Fixes an issue when ``cms_page`` is not available (#153)
=> Bumped version to 2.3.1

CHANGELOG.rst, djangocms_link/__init__.py
* Fixed an issue where 'Page' object has no attribute 'site'
=> Bumped version to 2.6.1

.github/workflows/publish-to-live-pypi.yml, .github/workflows/publish-to-test-pypi.yml
Adds pypi actions for test/live package uploads.
=> ci: Added pypi actions

.github/workflows/publish-to-test-pypi.yml
Fix branch name trigger on test pypi workflow.
=> ci: Fix branch name of pypi test workflow
